### ISSUE TITLE
H1

### ISSUE THREAD

**Issue by pcchale** [LucasLatessa/PAW-2024#1]
https://github.com/LucasLatessa/PAW-2024/blob/10e15de35be7fd88df5a9edba5728799821bffa3/index.html#L16-L18

En toda seccion que tiene un header debe haber un titulo (h1 - h6). En este caso, como es el header del body, se entiende que debería de haber un H1.
En este caso la imagen representa el titulo de la página, es decir que tendría que estar como h1. Lo que no entra en conflicto con que quieran que sea un anchor y que además sea una imagen. Lo que tienen que pensar es que para aquellos que no "ven" la imagen el texto que pongan en el atributo alt va ha reemplazar a la imagen, por lo tanto, en este caso se convertiría en el texto del h1. Por eso, en vez de poner "Logo de RapidaGula" solo pondría "Rápida Gula".

**Comment by LucasLatessa** [comment]
Resuelto, gracias por la correccion!
