### ISSUE TITLE
Carrusel

### ISSUE THREAD

**Issue by pcchale** [LucasLatessa/PAW-2024#2]
https://github.com/LucasLatessa/PAW-2024/blob/10e15de35be7fd88df5a9edba5728799821bffa3/index.html#L35-L40

Varias situaciones aquí:
- no se usa un div. Normalmente esto es un section.
- El carrusel es un listado de imágenes en el cual puede ser importante el orden o no, por lo cual se debe implementar algún tad de listado.
- Las imágenes son contenido y no decorativas, por lo cual es necesario darle la entidad de figura. Además es muy probable que se quiera dar una descripción de la misma que será su figcaption
- Los button solo se maquetan dentro de un formulario. Igualemente en este caso representan una funcionalidad del carrusel y no la entrada de datos de los usuarios, por lo cual no se deben maquetar. Estas funcionalidades deben agregarse con JS porque si el navegador tiene desactivado el JS los botones se verían pero no funcionarían. 
En el maquetado solo se incluye el contenido, nada de cosas decorativas o componentes de interfaz gráfica.
- El texto alternativo no es lo suficientemente descriptivo de las imágenes.
-

**Comment by JosueGaticaOdato** [comment]
Resuelto!
