### ISSUE TITLE
Cual es la semántica

### ISSUE THREAD

**Issue by pcchale** [LucasLatessa/PAW-2024#3]
https://github.com/LucasLatessa/PAW-2024/blob/10e15de35be7fd88df5a9edba5728799821bffa3/index.html#L42-L56

Tengan en cuenta que es lo que están representado. A la larga esto es un botón que llama a "hacer un pedido".
Por lo tanto:
- La Imagen es decorativa. Por lo tanto no se maqueta. Eso se agrega por CSS (próxima práctica).
- Este llama a la acción o representa una "sección" o es uno de tantos llamados a la acción. Yo propondría una sección de "reservas" con varios articulos que sería cada uno de los llamados a la acción:
  - una para reservar mesa
  - otra para el pedido del delivery
  - etc.
- Como todo tag de sectioning tiene que tener un titulo. 
- Una recomendación: que todo sea un link, para que el usuario pueda hacer click donde quiera, no solo en el texto.

**Comment by JosueGaticaOdato** [comment]
Resuelto!
